### ISSUE TITLE
Incorrect OS Image label name

### ISSUE THREAD

**Issue by sean-freeman** [IBM/ocp4-upi-compute-powervs-ibmcloud#15]
Incorrect OS Image label name

### Problem

Code block uses incorrect OS Image `rhel-coreos-stable-amd64`, which should be `red-coreos-amd64-byol`

Impacted code block in file [image.tf#L96](https://github.com/IBM/ocp4-upi-compute-powervs-ibmcloud/blob/main/modules/5_image/image.tf#L96) with hardcoded value:
```hcl
resource "ibm_is_image" "worker_image_id" {
  depends_on       = [null_resource.upload_rhcos_image, ibm_cos_bucket.cos_bucket, ibm_iam_authorization_policy.policy]
  name             = "${var.name_prefix}-rhcos-img"
  href             = "cos://${local.cos_region}/${var.name_prefix}-mac-intel/${var.name_prefix}-rhcos.qcow2"
  operating_system = "rhel-coreos-stable-amd64"
  resource_group   = data.ibm_resource_group.resource_group.id

  //increase timeouts as this import may be cross-region
  timeouts {
    create = "45m"
  }
}
```

### Evidence from Web GUI

<img width="1051" alt="image" src="https://github.com/IBM/ocp4-upi-compute-powervs-ibmcloud/assets/1815807/e6e5524d-0a5e-443b-acec-db662302c730">
<img width="1047" alt="image" src="https://github.com/IBM/ocp4-upi-compute-powervs-ibmcloud/assets/1815807/e65efe16-a36c-41a8-b7cd-f081fc3b0869">

**Comment by prb112** [comment]
thanks @sean-freeman we'll update today.

**Comment by sean-freeman** [comment]
@prb112 No problem. After the change, the imported OS Image will be visible/usable from both Intel Virtual Servers and Intel Bare Metals.

**Comment by prb112** [comment]
Fix is merged
