### ISSUE TITLE
Attach public gateway if missing while reusing a pre-created VPC 

### ISSUE THREAD

**Issue by varad-ahirwadkar** [IBM/ocp4-upi-compute-powervs-ibmcloud#8]

**Comment by prb112** [comment]
We have no plans to add this feature. We will add a pre-requisite

**Comment by prb112** [comment]
Ended up doing it in a bash script

**Comment by Chandan-Abhyankar** [comment]
Hi Paul,
I did not get a chance to execute code, but some of my review comments looking at code
Should we be  using == for conditional check?

modules/1_vpc_gateway/files/public_gateway.sh
Line 45, if [ "${PG}" = "null" ]
Line 49, if [ "${ADD_GATEWAY}" = "true" ]
Line 52,56,60
e.g.
if [ "${Z1_COUNT}" != "0" ] && [ "ZONE_${VPC_ZONE}" = "ZONE_${Z1_ZONE}" ]
Line 75
if [ "${PG}" = "null" ]
Line 81
if [ "${ADD_GATEWAY}" = "true" ]
Line 84, 89, 94
if [ -z "${Z1_HAS_PG}" ] && [ "${Z1_COUNT}" != "0" ] && [ "ZONE_${VPC_ZONE}" = "ZONE_${Z1_ZONE}" ]

modules/1_vpc_gateway/pg.tf
We are using below mentioned location on bastion to store files for other modules.
/root/ocp4-upi-compute-powervs-ibmcloud/intel
Line 28, mkdir -p /root/ocp4-upi-compute-powervs-ibmcloud-vpc-gw/
For consistency, should we be using our standard location to store public gateway files?

modules/1_vpc_gateway/variables.tf
Do we need error message with count more than 1 [It should be more than 0]? Also at time, worker_1 can be 0 and worker_2 can be 1, so please cross-check lookup condition and error_message ]
 validation {
    condition     = lookup(var.worker_1, "count", 1) >= 1
    error_message = "The worker_1.count value must be greater than 1."
  }

Thanks,
Chandan

**Comment by prb112** [comment]
Hey Chandan

The equivalence tests are valid for bash. 

I've tested the following cases: 
- vpc_create_public_gateways=false
- vpc_create_public_gateways=true - no public gateway exists
- vpc_create_public_gateways=true - gateway exists
- vpc_create_public_gateways=true - bad public gateway 

```
bash public_gateway.sh "api-key" "us-east" \
  "resource-group" \
  "rdr-mac-example-demo" "true" \
  "1" "us-east-1" \
  "0" "us-east-2" \
  "0" "us-east-3"
```

We should be a-ok

Thanks

Paul
